# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'VideoFullScreenSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Masonry'
  # Pods for VideoFullScreenSample

  target 'VideoFullScreenSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VideoFullScreenSampleUITests' do
    # Pods for testing
  end

end
